# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 722e6a284f4e255fcb0fe6ff6c8b2babbee53fef92475a949612ea4044e7763796f98c5b1eb39ddba4fb2d1a8ab516624567f4a54d797ec0dd62650e76874f4f

test:
  secret_key_base: 945cd81749a14d12d6dd677fb968fec081078503387fd8994eda9b30f32ad3693148a8d393cb9b59b0f20978ebffba08253d2e8e3968a4efe85efee2a37ae4cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
